# Generated by Django 3.1.2 on 2020-10-16 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_auto_20201015_2314'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Genre',
            new_name='Bebida',
        ),
    ]
