# Generated by Django 3.1.2 on 2020-11-05 03:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pnombre', models.CharField(max_length=100)),
                ('papellido', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['papellido', 'pnombre'],
            },
        ),
        migrations.CreateModel(
            name='Preparacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_prep', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('receta', models.TextField(max_length=3000)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.autor')),
                ('preparacion', models.ManyToManyField(to='web.Preparacion')),
            ],
        ),
    ]
